name: camera_test_module
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  module:
    androidX: true
    androidPackage: com.example.camera_test_module
    iosBundleIdentifier: com.example.cameraTestModule
